AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    aws-sam-usage 
      Samples showing usage of AWS SAM CLI to create different AWS resources

Parameters:
    PingEnvKey:
        Description: 'Input parameter to the PingWithEnvVariableFunction'
        Type: 'String'
        Default: 'xyz'

Resources:
    ApiGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            DefinitionBody:
                swagger: '2.0'
                info:
                    version: '1.0'
                    title: 'AwsSamUsage'
                paths:
                    /ping:
                        x-amazon-apigateway-any-method:
                            responses: {}
                            x-amazon-apigateway-integration:
                                httpMethod: post
                                type: aws_proxy
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PingFunction.Arn}/invocations

    PingFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: .
            Handler: index.ping
            Runtime: nodejs12.x
    PingFunctionPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref PingFunction
            Principal: apigateway.amazonaws.com

    PingWithEnvVariableFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: .
            Handler: index.pingWithEnvVariable
            Runtime: nodejs12.x
            Environment:
                Variables:
                    PING_ENV_KEY: !Ref PingEnvKey
